########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_BOX_NAME = 'ubuntu/trusty64'

Vagrant.configure('2') do |config|

  ip = '10.2.2.7'

  config.vm.define :influx do |influx|
    influx.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    influx.vm.box = BASE_BOX_NAME
    influx.vm.hostname = 'influxdb'
    influx.vm.network :private_network, ip: ip
    influx.vm.network "forwarded_port", :guest => 8083, :host => 8083
    influx.vm.network "forwarded_port", :guest => 8086, :host => 8086
    influx.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.privileged = false
    end
  end
end
